name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

    steps:
      - name: Create dotenv file
        run: |
          touch .env
          echo VITE_API_KEY = $VITE_API_KEY >> .env
      - name: check env file
        run: |
          cat .env | awk '$1=$1' FS= OFS=" "