name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

    steps:
      - name: display
        run: |
          echo "$VITE_API_KEY" |  awk '$1=$1' FS= OFS=" "
          
          touch .env
          echo VITE_API_KEY = $VITE_API_KEY >> .env
          
          cat .env | awk '$1=$1' FS= OFS=" "